Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ClassLength:
  Max: 125

Lint/UselessAssignment:
  Enabled: false

Style/ClassVars:
  Enabled: false
